# Generated by Django 5.2.8 on 2026-01-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registrationotp_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinesale',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
