# Generated by Django 5.2.8 on 2026-01-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_medicinesale_mfg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinesale',
            name='mfg_date',
        ),
        migrations.AddField(
            model_name='medicine',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
