# Generated by Django 5.2.8 on 2026-01-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_medicinesale_mfg_date_medicine_mfg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_to',
            field=models.TimeField(),
        ),
    ]
